wheel_radius: 0.033
track_width: 0.16
collision_radius: 0.11
motor_cmd_to_radsec: 0.024
motor_cmd_max: 265
encoder_ticks_to_rad: 0.00153398
body_id: "base_footprint"
odom_id: "odom"
wheel_left: "wheel_joint_left"
wheel_right: "wheel_joint_right"
