nusim:
  obstacles:
    radius: 0.038
    height: 0.25
    obs_x: [-0.6, 0.6, 0.6]
    obs_y: [-0.8, -0.8, 0.8]
  x0: -0.6
  y0: 0.8
  theta0: 1.57 
  x_length: 5.0
  y_length: 5.0
  vnoise_mean: 0.0
  vnoise_stddev: 0.01
  slip_min: 0.0
  slip_max: 1.0