nusim:
  obstacles:
    radius: 0.038
    height: 0.25
    obs_x: [-0.6, 0.6, 0.6]
    obs_y: [-0.8, -0.8, 0.8]
  x0: -0.6
  y0: 0.8
  theta0: 1.57 
  x_length: 5.0
  y_length: 5.0
  vnoise_mean: 0.0
  vnoise_stddev: 0.00
  slip_min: 0.0
  slip_max: 0.0
  basic_sensor_variance: 0.00
  sensor:
    angle_min: 0
    angle_max: 6.28319
    angle_increment: 0.017453
    time_increment: 0.00055555555
    scan_time: 0.2
    range_min: 0.12
    range_max: 3.5
    noise_level: 0.01
    num_samples: 360